trigger:
  stage: trigger
  rules:
    - if: $TRIGGER_CONFIGURATION == null
      when: never
    - if: $LAUNCH_FEATURE !~ /trigger-project/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-clean-/
      when: never
    - when: always
  tags:
    - $RUNNER_TAGS
  needs:
    - get-files-from-git
  image: ${REGISTRY_DOMAIN}${CICD_NAMESPACE}${PYTHON_PROCESS_PATH}:${PYTHON_PROCESS_TAG}
  script:
    - echo TRIGGER_CONFIGURATION -- $TRIGGER_CONFIGURATION
    - cd ${CICD_SCRIPT_FOLDER}
    - python3 -m ${PYTHON_TRIGGER_SCRIPT_PACKAGE}
      --token ${CI_JOB_TOKEN}
      --project ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
      --branch ${CI_COMMIT_BRANCH}
      --description "${CI_COMMIT_MESSAGE}"
      --changes-info-file ${CHANGES_INFO}
